### ISSUE TITLE
Rename robosuite_menagerie to robosuite_models and publish it to PyPi

### ISSUE THREAD

**Issue by zhuyifengzju** [ARISE-Initiative/robosuite_models#1]

**Comment by kevin-thankyou-lin** [comment]
Potentially enable `pip install robosuite[menagerie]` (great idea @abhihjoshi)

**Comment by kevin-thankyou-lin** [comment]
Yuke: relationship between `robosuite_menagerie` and `mujoco_menagerie`?
Soroush: how to do versioning?
You Liang: maybe have a xml parser for mujoco menagerie and specify conversion steps need to convert mujoco menagerie to robosuite.

**Comment by kevin-thankyou-lin** [comment]
@abhihjoshi create issue for object location init depends on the robot --- not initalizaed properly

**Comment by zhuyifengzju** [comment]
I believe this is fixed in a PR？
